### ISSUE TITLE
About filter out meaningless hidden states.

### ISSUE THREAD

**Issue by Martin-top** [hobincar/RecNet#23]
Hi,

I have noticed that you use two solutions to filter out meaningless hidden states in `forward_global_reconstructor` and `forward_local_reconstructor`, respectively. I have some questions for you about this.

(1) I wonder why you don't filter `local_reconstructor` for meaningless hidden state in the same way as `global_reconstructor`?
```
global_reconstructor:

    def forward_global_reconstructor(self, batch_size, decoder_hiddens, caption_masks):
        def mean_pool_hiddens(hiddens, caption_masks):
                                                      .....
            caption_masks = caption_masks.unsqueeze(2).expand_as(hiddens).type_as(hiddens)
            hiddens_masked = caption_masks * hiddens
                                                      .....
```
```
local_reconstructor:

 def forward(self, hidden, feats, masks=None):
                                .....
        energies = self.w(torch.tanh(Wh + Uv + self.b))
        if masks is not None:
            energies = energies.squeeze(2)
            energies[~masks] = -float('inf')
            energies = energies.unsqueeze(2)
        weights = F.softmax(energies, dim=1)
```
(2)Does the following line of code mean to filter out all `<PAD>` and `<EOS>` in the generated sentence? Or just filter out `<PAD>` after `<EOS>` and `<EOS>`?
```
caption_masks = (captions != self.vocab.word2idx['<PAD>']) * (captions != seself.vocab.word2idx['<EOS>'])
```
```
caption_generator.py:

    def forward(self, feats, captions=None, teacher_forcing_ratio=0.):
                                                       ....
        if captions is None:
            _, captions = outputs.max(dim=2)
        caption_masks = (captions != self.vocab.word2idx['<PAD>']) * (captions != self.vocab.word2idx['<EOS>'])
        caption_masks = caption_masks.cuda()
                                                      ....
```

**Comment by hobincar** [comment]
Hi.

(1) The global reconstructor uses the mean of all hidden states as input. Therefore, we can zero out the meaningless hidden state, aggregate them by summation, and divide by the number of valid (not meaningless) hidden states. For the case of local reconstructor, we should set the attention weights of the meaningless hidden states to be zero, not the meaningless hidden states themselves.

We can apply the same filtering to both reconstructors If we can just discard the meaningless states. However, this is technically impossible because all hidden state sets in the mini-batch must be treated as one tensor.

(2) What I intended was filtering out all `<PAD>` and `<EOS>` tokens.
