### ISSUE TITLE
Some problems with caption_generator.py

### ISSUE THREAD

**Issue by maoao686868** [hobincar/RecNet#36]
Sorry to disturb you again @hobincar , when I read carefully about the caption_generator.py. I found the variable"caption_mask", I don't know its function, may you tell me ? Thanks very much.
` if captions is None:
            _, captions = outputs.max(dim=2)
            # print(captions.shape)
        caption_masks = (captions != self.vocab.word2idx['<PAD>']) * (captions != self.vocab.word2idx['<EOS>'])
        caption_masks = caption_masks.cuda()
        # print(caption_masks.shape)
        feats_recon = None
        if self.reconstructor is not None:
            feats_recon = self.forward_reconstructor(batch_size, decoder_hiddens, caption_masks)
        return outputs, feats_recon`

**Comment by hobincar** [comment]
Hi @maoao686868.

The `caption_mask` is defined to mask out meaningless hidden states from the decoder. 

Since the model forwards all the samples in a mini-batch and each sample has a different number of words, the decoder generates more hidden states than the caption words. In other words, there are hidden states that are generated by taking `<EOS>` or `<PAD>` as an input token, which should be ignored by the reconstructor. To this end, each element of `caption_mask` is defined to be 1 if the corresponding input token is neither `<EOS>` nor `<PAD>`, or 0 otherwise ([code](https://github.com/hobincar/RecNet/blob/master/models/caption_generator.py#L105)). Then, the reconstructor can choose which hidden states to take or discard based on it (e.g, [here](https://github.com/hobincar/RecNet/blob/master/models/caption_generator.py#L53) for the global reconstructor).

**Comment by maoao686868** [comment]
Thanks a lot .You are so helpful that I appreciate very much. I have understood.
